controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    base_link_to_link1_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

base_link_to_link1_controller:
  ros__parameters:
    joints:
      - base_link_to_link1
    interface_name: position
